services:
  app:
    build: .
    container_name: xnet-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      WHATSAPP_ENABLED: "true"
      WHATSAPP_PROVIDER: "twilio"
      TWILIO_ACCOUNT_SID: "AC09e5a7c9b12d0ebd104552b30045b0e4"
      TWILIO_AUTH_TOKEN: "6e9c964ab42ad7c3100a6c5a3eb0ce9d"
      TWILIO_WHATSAPP_FROM: "whatsapp:+14195572878"
      TWILIO_MESSAGING_SERVICE_SID: "MGd03f7778f585a5adf76873037c009b26"
      WHATSAPP_TEMPLATE_NAME: "mytemplateinvoice"
      WHATSAPP_TEMPLATE_LANGUAGE_CODE: "en_US"
      TWILIO_CONTENT_SID: "HX2b1c610a6367c55059c95190739d9dc8"
      RABBITMQ_URL: "amqp://guest:guest@rabbitmq:5672"
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - backend_network
  
  #consumer:
  #  build: .
  #  container_name: user-actions-consumer
  #  command: node dist/userActionsConsumer.js
  #  depends_on:
  #    - rabbitmq
  #  networks:
  #    - backend_network

  redis:
    image: redis:latest
    container_name: redis-server
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - backend_network
  
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - "5672:5672"   # AMQP port
      - "15672:15672" # Management UI
      - "15674:15674" # WebSocket port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    command: >
      bash -c "rabbitmq-plugins enable rabbitmq_web_stomp &&
               rabbitmq-plugins enable rabbitmq_management &&
               rabbitmq-server"
    networks:
      - backend_network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s

networks:
  backend_network:
    driver: bridge

volumes:
  redis_data:
  node_modules_volume:
